steps:
  # Paso 1: Tu Hello World personalizado usando las sustituciones que inyectó el script
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "========================================================"
        echo "¡HELLO WORLD FROM GOOGLE CLOUD BUILD!"
        echo "========================================================"
        echo "It seems like everything work fine"

options:
  logging: CLOUD_LOGGING_ONLY